version: "3.7"
services:
  development:
    build:
      context: ../../../../to_do_list
      dockerfile: .infrastructure/docker/Dockerfile
    container_name: to-do
    command: bash -c "pipenv run pipenv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../../../../to_do_list:/usr/src/server
    ports:
      - "8000:8000"
    env_file:
      - ../../../.env.dev
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../../../.env.dev
volumes:
  postgres_data:
